[tasks.build]
run = "go build -o bin/cli cmd/cli/main.go"

[tasks.clean]
run = "rm -rf bin"

[tasks.test]
run = "go test -short ./..."

[tasks.test-integration]
run = "go test ./integration_tests"

[tasks.test-update-snapshots]
run = "UPDATE_SNAPS=true go test -short ./..."

[tasks.check]
run = """
go vet ./...
go fmt ./...
golangci-lint run
"""

[tasks.tidy]
run = "go mod tidy"

[tasks.docs-build]
dir = "docs"
run = "bun run build"

[tasks.docs-dev]
dir = "docs"
run = "bun run dev"

[tasks.run-frontend]
run = """
# syntax=docker.io/library/railpack-frontend2
echo 'FROM alpine:latest
RUN echo "Hello"' | docker buildx build -f - .
"""

[tasks.run-with-frontend]
run = "bun scripts/run-with-frontend.ts"

[tasks.build-and-push-frontend]
run = """
docker build -t railpack-frontend:latest \
  --label "org.opencontainers.image.source=https://github.com/railwayapp/railpack" \
  --label "org.opencontainers.image.description=BuildKit frontend for Railpack" \
  --label "org.opencontainers.image.licenses=MIT" \
  -f frontend.Dockerfile .

docker tag railpack-frontend:latest ghcr.io/railwayapp/railpack:railpack-frontend
docker push ghcr.io/railwayapp/railpack:railpack-frontend
"""

[tools]
go = "1.23.4"
golangci-lint = "1.63.4"
bun = "1.2"
